use_frameworks!

platform :ios, '8.0'

target 'HGPersonalCenterExtend' do
  pod 'HGPersonalCenterExtend', :path => '../'

  target 'HGPersonalCenterExtend_Tests' do
    inherit! :search_paths

    
  end
end
